# Numerical Python: NumPy

### NumPy Level 1

In [2]:
#once you give an alias u can use that everytime u import something from that module 
# without having to tyoe the word again
import numpy as np

In [13]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [5]:
np.zeros(5) #print an arraye of 5 zeros

array([0., 0., 0., 0., 0.])

In [7]:
#and then ones by
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.random.random(4)

array([0.8591721 , 0.31858687, 0.73038609, 0.65864948])

### NumPy Level 2

In [15]:
# 1D arrays
array1 = np.array([1,3,5])
array2 = np.ones(3)

In [16]:
#adding 2 arrays
array1 + array2

array([2., 4., 6.])

In [18]:
#mutiply
array1 * 2

array([ 2,  6, 10])

In [19]:
array2 * 3

array([3., 3., 3.])

### NumPy Level 3

In [21]:
#access item in the array 
array1[2]

5

### NumPy Level 4

In [22]:
#referreing to the arayy1 and array 2 made:

In [24]:
max(array1)

5

In [25]:
array1.min()

1

In [26]:
array1.sum()

9

In [28]:
array2.sum()

3.0

In [29]:
array2.mean()

1.0

### NumPy Level 5

In [31]:
#creating matrix
x = np.array([[2,3,4],[3,4,5],[4,5,6]])
x

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [35]:
#if you are making a matrix of ones
y = np.ones((3,4)) # rows, columns
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
z = np.zeros((5,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
k = np.random.random((3,4))
k

array([[0.54901407, 0.09770188, 0.76384512, 0.94675447],
       [0.83510066, 0.2611876 , 0.69435696, 0.6362371 ],
       [0.17349498, 0.52027461, 0.16244531, 0.45413772]])

### NumPy Level 6

In [52]:
j = np.array([[1,3],[4,5]])
i = np.array([[1,2],[3,4]])
i+j

array([[2, 5],
       [7, 9]])

In [56]:
t = np.dot(i,j) 
t

array([[ 9, 13],
       [19, 29]])

In [49]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b) #[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

array([[37, 40],
       [85, 92]])

In [58]:
t.max()

29

In [59]:
t.min()

9

### NumPy Level 7

In [60]:
#indexing for matrices

In [61]:
t

array([[ 9, 13],
       [19, 29]])

In [62]:
#access the element "13"
t[0,1] #0 crow, 1 column

13

In [64]:
#i can give range as wekk
t[0:2,1] #first 2 rows' 2nd column 

array([13, 29])

### NumPy Level 8

In [65]:
#reshaping arrays


In [79]:
#shaing an array to a matrix

x = np.array([1,2,3,4,5,6])
x.reshape(2,3) #2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

### NumPy Level 9

In [68]:
#multi dimensional array

In [72]:
x = np.array([[[10,11],[12,13]], [[2,3],[4,5]]])
x

array([[[10, 11],
        [12, 13]],

       [[ 2,  3],
        [ 4,  5]]])

In [74]:
np.ones((5,3,3)) #5 arrays of ones with 3 rows and 3 colums

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [76]:
np.zeros((5,3,1)) #5 arrays of zeroes with 3 rows and 1colums

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [80]:
import numpy as np 
 
x = np.array([1, 2, 3], dtype = complex)   # You can insert the type for value using dtype
 
print(x)

[1.+0.j 2.+0.j 3.+0.j]
